name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
    branches: [ chap4-roberta ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./chapter4/packaging-containers/Dockerfile
        push: false
        tags: andreaschandra/flask-roberta:latest

    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}