name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
    branches: [ chap4-roberta ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: andreaschandra/flask-roberta:latest